version: '3'
name: docker_dev
services:
  backend:
    container_name: docker_dev
    image: mochrira/dev:latest
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./examples:/var/www/html
    ports:
      - 9000:80