name: docker_dev
services:
  backend:
    container_name: docker_dev
    image: mochrira/dev:8.4-fpm-alpine3.21
    build: 
      context: ./
      dockerfile: dockerfile
    environment:
      - NG_INSTALL=NO
      - NG_VERSION=17
    volumes:
      - ./examples/workspace:/workspace
      - ./examples/before_startup.sh:/before_startup.sh
    ports:
      - 8080:80